/* Generated By:JavaCC: Do not edit this line. TraductorConstants.java */
package traductor;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TraductorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IF = 5;
  /** RegularExpression Id. */
  int ELSE = 6;
  /** RegularExpression Id. */
  int WHILE = 7;
  /** RegularExpression Id. */
  int FOR = 8;
  /** RegularExpression Id. */
  int DO = 9;
  /** RegularExpression Id. */
  int BREAK = 10;
  /** RegularExpression Id. */
  int CONTINUE = 11;
  /** RegularExpression Id. */
  int RETURN = 12;
  /** RegularExpression Id. */
  int SWITCH = 13;
  /** RegularExpression Id. */
  int CASE = 14;
  /** RegularExpression Id. */
  int DEFAULT_KW = 15;
  /** RegularExpression Id. */
  int TRUE = 16;
  /** RegularExpression Id. */
  int FALSE = 17;
  /** RegularExpression Id. */
  int NULL = 18;
  /** RegularExpression Id. */
  int PRINT = 19;
  /** RegularExpression Id. */
  int PRINTLN = 20;
  /** RegularExpression Id. */
  int FOREACH = 21;
  /** RegularExpression Id. */
  int IN = 22;
  /** RegularExpression Id. */
  int INT = 23;
  /** RegularExpression Id. */
  int BOOLEAN = 24;
  /** RegularExpression Id. */
  int STRING = 25;
  /** RegularExpression Id. */
  int CHAR = 26;
  /** RegularExpression Id. */
  int DOUBLE = 27;
  /** RegularExpression Id. */
  int FLOAT = 28;
  /** RegularExpression Id. */
  int LONG = 29;
  /** RegularExpression Id. */
  int SHORT = 30;
  /** RegularExpression Id. */
  int BYTE = 31;
  /** RegularExpression Id. */
  int MENOR_IGUAL = 32;
  /** RegularExpression Id. */
  int MAYOR_IGUAL = 33;
  /** RegularExpression Id. */
  int IGUALDAD = 34;
  /** RegularExpression Id. */
  int DIFERENTE = 35;
  /** RegularExpression Id. */
  int MENOR = 36;
  /** RegularExpression Id. */
  int MAYOR = 37;
  /** RegularExpression Id. */
  int SUMA = 38;
  /** RegularExpression Id. */
  int RESTA = 39;
  /** RegularExpression Id. */
  int MULT = 40;
  /** RegularExpression Id. */
  int DIV = 41;
  /** RegularExpression Id. */
  int MOD = 42;
  /** RegularExpression Id. */
  int ASIGNACION = 43;
  /** RegularExpression Id. */
  int INCREMENTO = 44;
  /** RegularExpression Id. */
  int DECREMENTO = 45;
  /** RegularExpression Id. */
  int AND_LOGICO = 46;
  /** RegularExpression Id. */
  int OR_LOGICO = 47;
  /** RegularExpression Id. */
  int NOT_LOGICO = 48;
  /** RegularExpression Id. */
  int PARENTESIS_IZQ = 49;
  /** RegularExpression Id. */
  int PARENTESIS_DER = 50;
  /** RegularExpression Id. */
  int LLAVE_IZQ = 51;
  /** RegularExpression Id. */
  int LLAVE_DER = 52;
  /** RegularExpression Id. */
  int CORCHETE_IZQ = 53;
  /** RegularExpression Id. */
  int CORCHETE_DER = 54;
  /** RegularExpression Id. */
  int PUNTO_Y_COMA = 55;
  /** RegularExpression Id. */
  int DOS_PUNTOS = 56;
  /** RegularExpression Id. */
  int COMA = 57;
  /** RegularExpression Id. */
  int PUNTO = 58;
  /** RegularExpression Id. */
  int DECIMAL = 59;
  /** RegularExpression Id. */
  int NUMERO = 60;
  /** RegularExpression Id. */
  int CADENA = 61;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 62;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"for\"",
    "\"do\"",
    "\"break\"",
    "\"continue\"",
    "\"return\"",
    "\"switch\"",
    "\"case\"",
    "\"default\"",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "\"print\"",
    "\"println\"",
    "\"foreach\"",
    "\"in\"",
    "\"int\"",
    "\"boolean\"",
    "\"string\"",
    "\"char\"",
    "\"double\"",
    "\"float\"",
    "\"long\"",
    "\"short\"",
    "\"byte\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"=\"",
    "\"++\"",
    "\"--\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\":\"",
    "\",\"",
    "\".\"",
    "<DECIMAL>",
    "<NUMERO>",
    "<CADENA>",
    "<IDENTIFICADOR>",
  };

}
