/* Generated By:JavaCC: Do not edit this line. Traductor.java */
package traductor;

import java.io.*;
import java.util.*;

/**
 * Traductor.jj
 * ------------
 * Extiende la gramática original de Analizador.jj: SIGUE reconociendo y
 * validando el mismo código C# (mismos tokens, mismas reglas, mismo
 * análisis léxico/semántico impreso por consola), pero además cada regla
 * ahora CONSTRUYE Y REGRESA un Nodo del AST en vez de ser "void".
 *
 * Ese árbol (Nodo "programa") es lo que luego recorren GeneradorPython y
 * GeneradorJavaScript para producir el código traducido.
 *
 * Qué cambié respecto a Analizador.jj:
 *   - Cada "void regla()" pasó a ser "Nodo regla()" y termina con
 *     "{ return nodo; }".
 *   - Se agregaron variables locales "Nodo n = new Nodo(\"tipo\")" y
 *     llamadas a n.agregar(...) / n.atributo(...) para ir armando el árbol.
 *   - mostrarToken(t) y regla(...) del original se conservan tal cual,
 *     así que la salida de consola con el detalle léxico/sintáctico sigue
 *     funcionando igual que antes.
 */
public class Traductor implements TraductorConstants {

    public static void regla(String r) {
        System.out.println("Regla: " + r);
    }

    public static void mostrarToken(Token t) {
        String palabra = t.image.toLowerCase();
        System.out.println("----------------------");
        if (Diccionario.mapa.containsKey(palabra)) {
            PalabraInfo info = Diccionario.mapa.get(palabra);
            System.out.println("Token: " + info.token);
            System.out.println("Expresion Regular: " + info.expresion);
            System.out.println("Lexema: " + t.image);
            if (info.lenguaje != null && !info.lenguaje.isEmpty())
                System.out.println("Lenguaje: " + info.lenguaje);
            if (info.clasificacion != null && !info.clasificacion.isEmpty())
                System.out.println("Clasificacion: " + info.clasificacion);
            if (info.funcion != null && !info.funcion.isEmpty())
                System.out.println("Funcion: " + info.funcion);
        } else {
            if (t.kind == IDENTIFICADOR) {
                System.out.println("Token: IDENTIFICADOR");
                System.out.println("Lexema: " + t.image);
            } else if (t.kind == NUMERO) {
                System.out.println("Token: NUMERO");
                System.out.println("Lexema: " + t.image);
            } else if (t.kind == DECIMAL) {
                System.out.println("Token: DECIMAL");
                System.out.println("Lexema: " + t.image);
            } else if (t.kind == CADENA) {
                System.out.println("Token: CADENA");
                System.out.println("Lexema: " + t.image);
            } else {
                System.out.println("Token: " + t.image);
                System.out.println("Lexema: " + t.image);
            }
        }
    }

// ======================================================
// GRAMATICA - cada regla ahora construye y regresa un Nodo
// ======================================================
  final public Nodo programa() throws ParseException {
  Nodo raiz = new Nodo("programa"); Nodo hijo;
    label_1:
    while (true) {
      hijo = instruccion();
                           raiz.agregar(hijo);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IF:
      case WHILE:
      case FOR:
      case DO:
      case BREAK:
      case CONTINUE:
      case RETURN:
      case SWITCH:
      case PRINT:
      case PRINTLN:
      case FOREACH:
      case INT:
      case BOOLEAN:
      case STRING:
      case CHAR:
      case DOUBLE:
      case FLOAT:
      case LONG:
      case SHORT:
      case BYTE:
      case LLAVE_IZQ:
      case IDENTIFICADOR:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
    }
    jj_consume_token(0);
      {if (true) return raiz;}
    throw new Error("Missing return statement in function");
  }

  final public Nodo instruccion() throws ParseException {
  Nodo n;
    if (jj_2_1(2)) {
      n = declaracionVariable();
    } else if (jj_2_2(2)) {
      n = asignacion();
    } else if (jj_2_3(2)) {
      n = incrementoDecremento();
    } else if (jj_2_4(2)) {
      n = condicion();
    } else if (jj_2_5(2)) {
      n = cicloMientras();
    } else if (jj_2_6(2)) {
      n = cicloPara();
    } else if (jj_2_7(2)) {
      n = cicloDoWhile();
    } else if (jj_2_8(2)) {
      n = cicloForeach();
    } else if (jj_2_9(2)) {
      n = estructuraSwitch();
    } else if (jj_2_10(2)) {
      n = escritura();
    } else if (jj_2_11(2)) {
      n = breakInstruccion();
    } else if (jj_2_12(2)) {
      n = continueInstruccion();
    } else if (jj_2_13(2)) {
      n = returnInstruccion();
    } else if (jj_2_14(2)) {
      n = bloque();
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
      {if (true) return n;}
    throw new Error("Missing return statement in function");
  }

// ------------------------------------------------------
// DECLARACION DE VARIABLES
// ------------------------------------------------------
  final public Nodo declaracionVariable() throws ParseException {
  Token t; Nodo n = new Nodo("declaracionVariable"); Nodo exp = null;
      regla("declaracionVariable -> tipo identificador (asignacion expresion)? puntocoma");
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INT:
      t = jj_consume_token(INT);
                        mostrarToken(t); n.atributo("tipoDato", "int");
      break;
    case BOOLEAN:
      t = jj_consume_token(BOOLEAN);
                        mostrarToken(t); n.atributo("tipoDato", "boolean");
      break;
    case STRING:
      t = jj_consume_token(STRING);
                        mostrarToken(t); n.atributo("tipoDato", "string");
      break;
    case CHAR:
      t = jj_consume_token(CHAR);
                        mostrarToken(t); n.atributo("tipoDato", "char");
      break;
    case DOUBLE:
      t = jj_consume_token(DOUBLE);
                        mostrarToken(t); n.atributo("tipoDato", "double");
      break;
    case FLOAT:
      t = jj_consume_token(FLOAT);
                        mostrarToken(t); n.atributo("tipoDato", "float");
      break;
    case LONG:
      t = jj_consume_token(LONG);
                        mostrarToken(t); n.atributo("tipoDato", "long");
      break;
    case SHORT:
      t = jj_consume_token(SHORT);
                        mostrarToken(t); n.atributo("tipoDato", "short");
      break;
    case BYTE:
      t = jj_consume_token(BYTE);
                        mostrarToken(t); n.atributo("tipoDato", "byte");
      break;
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    t = jj_consume_token(IDENTIFICADOR);
        mostrarToken(t);
        n.valor = t.image;
        Semantico.declararVariable(t.image, n.atributoPorDefecto("tipoDato", "variable"));
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ASIGNACION:
      t = jj_consume_token(ASIGNACION);
                         mostrarToken(t);
      exp = expresion();
                          n.agregar(exp);
      break;
    default:
      jj_la1[2] = jj_gen;
      ;
    }
    t = jj_consume_token(PUNTO_Y_COMA);
                       mostrarToken(t); {if (true) return n;}
    throw new Error("Missing return statement in function");
  }

// ------------------------------------------------------
// ASIGNACION
// ------------------------------------------------------
  final public Nodo asignacion() throws ParseException {
  Token t; Nodo n = new Nodo("asignacion"); Nodo exp;
      regla("asignacion -> identificador asignacion expresion puntocoma");
    t = jj_consume_token(IDENTIFICADOR);
                        mostrarToken(t); n.valor = t.image;
    t = jj_consume_token(ASIGNACION);
                     mostrarToken(t);
    exp = expresion();
                      n.agregar(exp);
    t = jj_consume_token(PUNTO_Y_COMA);
                       mostrarToken(t); {if (true) return n;}
    throw new Error("Missing return statement in function");
  }

// ------------------------------------------------------
// INCREMENTO / DECREMENTO
// ------------------------------------------------------
  final public Nodo incrementoDecremento() throws ParseException {
  Token t; Nodo n = new Nodo("incrementoDecremento");
    t = jj_consume_token(IDENTIFICADOR);
        mostrarToken(t);
        n.valor = t.image;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INCREMENTO:
      t = jj_consume_token(INCREMENTO);
            mostrarToken(t);
            n.atributo("operador", "++");
      break;
    case DECREMENTO:
      t = jj_consume_token(DECREMENTO);
            mostrarToken(t);
            n.atributo("operador", "--");
      break;
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    t = jj_consume_token(PUNTO_Y_COMA);
        mostrarToken(t);
        {if (true) return n;}
    throw new Error("Missing return statement in function");
  }

// ------------------------------------------------------
// IF - ELSE
// ------------------------------------------------------
  final public Nodo condicion() throws ParseException {
  Token t; Nodo n = new Nodo("condicion"); Nodo cond, bIf, bElse;
      regla("condicion -> if ( expresionLogica ) bloque ( else bloque )?");
    t = jj_consume_token(IF);
             mostrarToken(t);
    t = jj_consume_token(PARENTESIS_IZQ);
                         mostrarToken(t);
    cond = expresionLogica();
                             n.agregar(cond);
    t = jj_consume_token(PARENTESIS_DER);
                         mostrarToken(t);
    bIf = bloque();
                   n.agregar(bIf);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ELSE:
      t = jj_consume_token(ELSE);
                   mostrarToken(t); n.atributo("tieneElse", "true");
      bElse = bloque();
                         n.agregar(bElse);
      break;
    default:
      jj_la1[4] = jj_gen;
      ;
    }
      {if (true) return n;}
    throw new Error("Missing return statement in function");
  }

// ------------------------------------------------------
// WHILE
// ------------------------------------------------------
  final public Nodo cicloMientras() throws ParseException {
  Token t; Nodo n = new Nodo("cicloMientras"); Nodo cond, cuerpo;
      regla("cicloMientras -> while ( expresionLogica ) bloque");
    t = jj_consume_token(WHILE);
                mostrarToken(t);
    t = jj_consume_token(PARENTESIS_IZQ);
                         mostrarToken(t);
    cond = expresionLogica();
                             n.agregar(cond);
    t = jj_consume_token(PARENTESIS_DER);
                         mostrarToken(t);
    cuerpo = bloque();
                      n.agregar(cuerpo); {if (true) return n;}
    throw new Error("Missing return statement in function");
  }

// ------------------------------------------------------
// DO-WHILE
// ------------------------------------------------------
  final public Nodo cicloDoWhile() throws ParseException {
  Token t; Nodo n = new Nodo("cicloDoWhile"); Nodo cuerpo, cond;
      regla("cicloDoWhile -> do bloque while ( expresionLogica ) puntocoma");
    t = jj_consume_token(DO);
             mostrarToken(t);
    cuerpo = bloque();
                      n.agregar(cuerpo);
    t = jj_consume_token(WHILE);
                mostrarToken(t);
    t = jj_consume_token(PARENTESIS_IZQ);
                         mostrarToken(t);
    cond = expresionLogica();
                             n.agregar(cond);
    t = jj_consume_token(PARENTESIS_DER);
                         mostrarToken(t);
    t = jj_consume_token(PUNTO_Y_COMA);
                       mostrarToken(t); {if (true) return n;}
    throw new Error("Missing return statement in function");
  }

// ------------------------------------------------------
// FOREACH
// ------------------------------------------------------
  final public Nodo cicloForeach() throws ParseException {
  Token t; Nodo n = new Nodo("cicloForeach"); Nodo cuerpo;
      regla("cicloForeach -> foreach ( tipo identificador in coleccion ) bloque");
    t = jj_consume_token(FOREACH);
                  mostrarToken(t);
    t = jj_consume_token(PARENTESIS_IZQ);
                         mostrarToken(t);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INT:
      t = jj_consume_token(INT);
                        mostrarToken(t); n.atributo("tipoDato", "int");
      break;
    case STRING:
      t = jj_consume_token(STRING);
                        mostrarToken(t); n.atributo("tipoDato", "string");
      break;
    case BOOLEAN:
      t = jj_consume_token(BOOLEAN);
                        mostrarToken(t); n.atributo("tipoDato", "boolean");
      break;
    default:
      jj_la1[5] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    t = jj_consume_token(IDENTIFICADOR);
                        mostrarToken(t); n.valor = t.image;
    t = jj_consume_token(IN);
             mostrarToken(t);
    t = jj_consume_token(IDENTIFICADOR);
                        mostrarToken(t); n.atributo("coleccion", t.image);
    t = jj_consume_token(PARENTESIS_DER);
                         mostrarToken(t);
    cuerpo = bloque();
                      n.agregar(cuerpo); {if (true) return n;}
    throw new Error("Missing return statement in function");
  }

// ------------------------------------------------------
// SWITCH
// ------------------------------------------------------
  final public Nodo estructuraSwitch() throws ParseException {
  Token t; Nodo n = new Nodo("estructuraSwitch"); Nodo exp, caso;
      regla("switch -> switch ( expresion ) { casos+ default? }");
    t = jj_consume_token(SWITCH);
                 mostrarToken(t);
    t = jj_consume_token(PARENTESIS_IZQ);
                         mostrarToken(t);
    exp = expresion();
                      n.agregar(exp);
    t = jj_consume_token(PARENTESIS_DER);
                         mostrarToken(t);
    t = jj_consume_token(LLAVE_IZQ);
                    mostrarToken(t);
    label_2:
    while (true) {
      caso = casoSwitch();
                          n.agregar(caso);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CASE:
        ;
        break;
      default:
        jj_la1[6] = jj_gen;
        break label_2;
      }
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case DEFAULT_KW:
      caso = casoDefaultSwitch();
                                 n.agregar(caso);
      break;
    default:
      jj_la1[7] = jj_gen;
      ;
    }
    t = jj_consume_token(LLAVE_DER);
                    mostrarToken(t); {if (true) return n;}
    throw new Error("Missing return statement in function");
  }

  final public Nodo casoSwitch() throws ParseException {
  Token t; Nodo n = new Nodo("casoSwitch"); Nodo val, inst;
      regla("caso -> case valor : instrucciones");
    t = jj_consume_token(CASE);
               mostrarToken(t);
    val = valor();
                  n.agregar(val);
    t = jj_consume_token(DOS_PUNTOS);
                     mostrarToken(t);
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IF:
      case WHILE:
      case FOR:
      case DO:
      case BREAK:
      case CONTINUE:
      case RETURN:
      case SWITCH:
      case PRINT:
      case PRINTLN:
      case FOREACH:
      case INT:
      case BOOLEAN:
      case STRING:
      case CHAR:
      case DOUBLE:
      case FLOAT:
      case LONG:
      case SHORT:
      case BYTE:
      case LLAVE_IZQ:
      case IDENTIFICADOR:
        ;
        break;
      default:
        jj_la1[8] = jj_gen;
        break label_3;
      }
      inst = instruccion();
                           n.agregar(inst);
    }
      {if (true) return n;}
    throw new Error("Missing return statement in function");
  }

  final public Nodo casoDefaultSwitch() throws ParseException {
  Token t; Nodo n = new Nodo("casoDefault"); Nodo inst;
      regla("default -> default : instrucciones");
    t = jj_consume_token(DEFAULT_KW);
                     mostrarToken(t);
    t = jj_consume_token(DOS_PUNTOS);
                     mostrarToken(t);
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IF:
      case WHILE:
      case FOR:
      case DO:
      case BREAK:
      case CONTINUE:
      case RETURN:
      case SWITCH:
      case PRINT:
      case PRINTLN:
      case FOREACH:
      case INT:
      case BOOLEAN:
      case STRING:
      case CHAR:
      case DOUBLE:
      case FLOAT:
      case LONG:
      case SHORT:
      case BYTE:
      case LLAVE_IZQ:
      case IDENTIFICADOR:
        ;
        break;
      default:
        jj_la1[9] = jj_gen;
        break label_4;
      }
      inst = instruccion();
                           n.agregar(inst);
    }
      {if (true) return n;}
    throw new Error("Missing return statement in function");
  }

// ------------------------------------------------------
// BREAK, CONTINUE, RETURN
// ------------------------------------------------------
  final public Nodo breakInstruccion() throws ParseException {
  Token t;
      regla("break -> break puntocoma");
    t = jj_consume_token(BREAK);
                mostrarToken(t);
    t = jj_consume_token(PUNTO_Y_COMA);
                       mostrarToken(t); {if (true) return new Nodo("breakInstruccion");}
    throw new Error("Missing return statement in function");
  }

  final public Nodo continueInstruccion() throws ParseException {
  Token t;
      regla("continue -> continue puntocoma");
    t = jj_consume_token(CONTINUE);
                   mostrarToken(t);
    t = jj_consume_token(PUNTO_Y_COMA);
                       mostrarToken(t); {if (true) return new Nodo("continueInstruccion");}
    throw new Error("Missing return statement in function");
  }

  final public Nodo returnInstruccion() throws ParseException {
  Token t; Nodo n = new Nodo("returnInstruccion"); Nodo exp;
      regla("return -> return (expresion)? puntocoma");
    t = jj_consume_token(RETURN);
                 mostrarToken(t);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TRUE:
    case FALSE:
    case NULL:
    case RESTA:
    case PARENTESIS_IZQ:
    case DECIMAL:
    case NUMERO:
    case CADENA:
    case IDENTIFICADOR:
      exp = expresion();
                        n.agregar(exp);
      break;
    default:
      jj_la1[10] = jj_gen;
      ;
    }
    t = jj_consume_token(PUNTO_Y_COMA);
                       mostrarToken(t); {if (true) return n;}
    throw new Error("Missing return statement in function");
  }

// ------------------------------------------------------
// FOR
// ------------------------------------------------------
  final public Nodo cicloPara() throws ParseException {
  Token t; Nodo n = new Nodo("cicloPara"); Nodo init, cond, upd, cuerpo;
      regla("cicloPara -> for ( asignacionSimple ; expresionLogica ; asignacionSimple ) bloque");
    t = jj_consume_token(FOR);
              mostrarToken(t);
    t = jj_consume_token(PARENTESIS_IZQ);
                         mostrarToken(t);
    init = asignacionSimple();
                              n.agregar(init);
    t = jj_consume_token(PUNTO_Y_COMA);
                       mostrarToken(t);
    cond = expresionLogica();
                             n.agregar(cond);
    t = jj_consume_token(PUNTO_Y_COMA);
                       mostrarToken(t);
    upd = asignacionSimple();
                             n.agregar(upd);
    t = jj_consume_token(PARENTESIS_DER);
                         mostrarToken(t);
    cuerpo = bloque();
                      n.agregar(cuerpo); {if (true) return n;}
    throw new Error("Missing return statement in function");
  }

  final public Nodo asignacionSimple() throws ParseException {
  Token t; Nodo n = new Nodo("asignacionSimple"); Nodo exp;
    t = jj_consume_token(IDENTIFICADOR);
                        mostrarToken(t); n.valor = t.image;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ASIGNACION:
      t = jj_consume_token(ASIGNACION);
            mostrarToken(t);
      exp = expresion();
            n.agregar(exp);
            n.atributo("operadorAsignacion", "=");
      break;
    case INCREMENTO:
      t = jj_consume_token(INCREMENTO);
            mostrarToken(t);
            n.atributo("operadorAsignacion", "++");
      break;
    case DECREMENTO:
      t = jj_consume_token(DECREMENTO);
            mostrarToken(t);
            n.atributo("operadorAsignacion", "--");
      break;
    default:
      jj_la1[11] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
      {if (true) return n;}
    throw new Error("Missing return statement in function");
  }

// ------------------------------------------------------
// PRINT
// ------------------------------------------------------
  final public Nodo escritura() throws ParseException {
  Token t; Nodo n = new Nodo("escritura"); Nodo exp;
      regla("escritura -> print ( expresion ) puntocoma");
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PRINT:
      t = jj_consume_token(PRINT);
                        mostrarToken(t); n.atributo("variante", "print");
      break;
    case PRINTLN:
      t = jj_consume_token(PRINTLN);
                        mostrarToken(t); n.atributo("variante", "println");
      break;
    default:
      jj_la1[12] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    t = jj_consume_token(PARENTESIS_IZQ);
                         mostrarToken(t);
    exp = expresion();
                      n.agregar(exp);
    t = jj_consume_token(PARENTESIS_DER);
                         mostrarToken(t);
    t = jj_consume_token(PUNTO_Y_COMA);
                       mostrarToken(t); {if (true) return n;}
    throw new Error("Missing return statement in function");
  }

// ------------------------------------------------------
// BLOQUE
// ------------------------------------------------------
  final public Nodo bloque() throws ParseException {
  Token t; Nodo n = new Nodo("bloque"); Nodo inst;
      regla("bloque -> { instrucciones* }");
    t = jj_consume_token(LLAVE_IZQ);
                    mostrarToken(t);
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IF:
      case WHILE:
      case FOR:
      case DO:
      case BREAK:
      case CONTINUE:
      case RETURN:
      case SWITCH:
      case PRINT:
      case PRINTLN:
      case FOREACH:
      case INT:
      case BOOLEAN:
      case STRING:
      case CHAR:
      case DOUBLE:
      case FLOAT:
      case LONG:
      case SHORT:
      case BYTE:
      case LLAVE_IZQ:
      case IDENTIFICADOR:
        ;
        break;
      default:
        jj_la1[13] = jj_gen;
        break label_5;
      }
      inst = instruccion();
                           n.agregar(inst);
    }
    t = jj_consume_token(LLAVE_DER);
                    mostrarToken(t); {if (true) return n;}
    throw new Error("Missing return statement in function");
  }

// ------------------------------------------------------
// EXPRESIONES LOGICAS
// ------------------------------------------------------
  final public Nodo expresionLogica() throws ParseException {
  Nodo n;
    n = expresionOr();
      {if (true) return n;}
    throw new Error("Missing return statement in function");
  }

  final public Nodo expresionOr() throws ParseException {
  Nodo izquierdo, derecho, n; Token t;
    izquierdo = expresionAnd();
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OR_LOGICO:
        ;
        break;
      default:
        jj_la1[14] = jj_gen;
        break label_6;
      }
      t = jj_consume_token(OR_LOGICO);
            mostrarToken(t);
      derecho = expresionAnd();
            n = new Nodo("expresionLogica");
            n.atributo("operador", "||");
            n.agregar(izquierdo);
            n.agregar(derecho);
            izquierdo = n;
    }
      {if (true) return izquierdo;}
    throw new Error("Missing return statement in function");
  }

  final public Nodo expresionAnd() throws ParseException {
  Nodo izquierdo, derecho, n; Token t;
    izquierdo = expresionNot();
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AND_LOGICO:
        ;
        break;
      default:
        jj_la1[15] = jj_gen;
        break label_7;
      }
      t = jj_consume_token(AND_LOGICO);
            mostrarToken(t);
      derecho = expresionNot();
            n = new Nodo("expresionLogica");
            n.atributo("operador", "&&");
            n.agregar(izquierdo);
            n.agregar(derecho);
            izquierdo = n;
    }
      {if (true) return izquierdo;}
    throw new Error("Missing return statement in function");
  }

  final public Nodo expresionNot() throws ParseException {
  Nodo n; Token t; Nodo resultado;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NOT_LOGICO:
      t = jj_consume_token(NOT_LOGICO);
          mostrarToken(t);
      n = expresionNot();
          resultado = new Nodo("expresionLogica");
          resultado.atributo("operador", "!");
          resultado.agregar(n);
          {if (true) return resultado;}
      break;
    case PARENTESIS_IZQ:
      t = jj_consume_token(PARENTESIS_IZQ);
          mostrarToken(t);
      n = expresionLogica();

      t = jj_consume_token(PARENTESIS_DER);
          mostrarToken(t);
          resultado = new Nodo("agrupacion");
          resultado.agregar(n);
          {if (true) return resultado;}
      break;
    case TRUE:
    case FALSE:
    case NULL:
    case RESTA:
    case DECIMAL:
    case NUMERO:
    case CADENA:
    case IDENTIFICADOR:
      n = expresionRelacional();
          {if (true) return n;}
      break;
    default:
      jj_la1[16] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public Nodo expresionRelacional() throws ParseException {
  Nodo izquierdo, derecho, n; String op;
    izquierdo = expresion();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MENOR_IGUAL:
    case MAYOR_IGUAL:
    case IGUALDAD:
    case DIFERENTE:
    case MENOR:
    case MAYOR:
      op = operadorRelacional();
      derecho = expresion();
            n = new Nodo("expresionLogica");
            n.atributo("operador", op);
            n.agregar(izquierdo);
            n.agregar(derecho);
            {if (true) return n;}
      break;
    default:
      jj_la1[17] = jj_gen;
      ;
    }
        {if (true) return izquierdo;}
    throw new Error("Missing return statement in function");
  }

  final public String operadorRelacional() throws ParseException {
  Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MENOR:
      t = jj_consume_token(MENOR);
                         mostrarToken(t); {if (true) return "<";}
      break;
    case MAYOR:
      t = jj_consume_token(MAYOR);
                          mostrarToken(t); {if (true) return ">";}
      break;
    case MENOR_IGUAL:
      t = jj_consume_token(MENOR_IGUAL);
                          mostrarToken(t); {if (true) return "<=";}
      break;
    case MAYOR_IGUAL:
      t = jj_consume_token(MAYOR_IGUAL);
                          mostrarToken(t); {if (true) return ">=";}
      break;
    case IGUALDAD:
      t = jj_consume_token(IGUALDAD);
                          mostrarToken(t); {if (true) return "==";}
      break;
    case DIFERENTE:
      t = jj_consume_token(DIFERENTE);
                          mostrarToken(t); {if (true) return "!=";}
      break;
    default:
      jj_la1[18] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

// ------------------------------------------------------
// EXPRESIONES ARITMETICAS
// ------------------------------------------------------
  final public Nodo expresion() throws ParseException {
  Nodo n;
    n = expresionAditiva();
      {if (true) return n;}
    throw new Error("Missing return statement in function");
  }

  final public Nodo expresionAditiva() throws ParseException {
  Nodo izquierdo, derecho, n; String op;
    izquierdo = expresionMultiplicativa();
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SUMA:
      case RESTA:
        ;
        break;
      default:
        jj_la1[19] = jj_gen;
        break label_8;
      }
      op = operadorSumaResta();
      derecho = expresionMultiplicativa();
            n = new Nodo("expresion");
            n.atributo("operador", op);
            n.agregar(izquierdo);
            n.agregar(derecho);
            izquierdo = n;

            regla("expresion -> " + op);
    }
      {if (true) return izquierdo;}
    throw new Error("Missing return statement in function");
  }

  final public Nodo expresionMultiplicativa() throws ParseException {
  Nodo izquierdo, derecho, n; String op;
    izquierdo = expresionUnaria();
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MULT:
      case DIV:
      case MOD:
        ;
        break;
      default:
        jj_la1[20] = jj_gen;
        break label_9;
      }
      op = operadorMultiplicativo();
      derecho = expresionUnaria();
            n = new Nodo("expresion");
            n.atributo("operador", op);
            n.agregar(izquierdo);
            n.agregar(derecho);
            izquierdo = n;

            regla("expresion -> " + op);
    }
      {if (true) return izquierdo;}
    throw new Error("Missing return statement in function");
  }

  final public Nodo expresionUnaria() throws ParseException {
  Nodo n; Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case RESTA:
      t = jj_consume_token(RESTA);
          mostrarToken(t);
      n = expresionUnaria();
          Nodo resultado = new Nodo("expresion");
          resultado.atributo("operador", "unario-");
          resultado.agregar(n);
          {if (true) return resultado;}
      break;
    case TRUE:
    case FALSE:
    case NULL:
    case PARENTESIS_IZQ:
    case DECIMAL:
    case NUMERO:
    case CADENA:
    case IDENTIFICADOR:
      n = expresionPrimaria();
          {if (true) return n;}
      break;
    default:
      jj_la1[21] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public Nodo expresionPrimaria() throws ParseException {
  Nodo n; Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TRUE:
    case FALSE:
    case NULL:
    case DECIMAL:
    case NUMERO:
    case CADENA:
    case IDENTIFICADOR:
      n = valor();
        {if (true) return n;}
      break;
    case PARENTESIS_IZQ:
      t = jj_consume_token(PARENTESIS_IZQ);
          mostrarToken(t);
      n = expresion();

      t = jj_consume_token(PARENTESIS_DER);
          mostrarToken(t);
          Nodo resultado = new Nodo("agrupacion");
          resultado.agregar(n);
          {if (true) return resultado;}
      break;
    default:
      jj_la1[22] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public String operadorSumaResta() throws ParseException {
  Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SUMA:
      t = jj_consume_token(SUMA);
                  mostrarToken(t); {if (true) return "+";}
      break;
    case RESTA:
      t = jj_consume_token(RESTA);
                  mostrarToken(t); {if (true) return "-";}
      break;
    default:
      jj_la1[23] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public String operadorMultiplicativo() throws ParseException {
  Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MULT:
      t = jj_consume_token(MULT);
                 mostrarToken(t); {if (true) return "*";}
      break;
    case DIV:
      t = jj_consume_token(DIV);
                 mostrarToken(t); {if (true) return "/";}
      break;
    case MOD:
      t = jj_consume_token(MOD);
                 mostrarToken(t); {if (true) return "%";}
      break;
    default:
      jj_la1[24] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public String operadorAritmetico() throws ParseException {
  Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SUMA:
      t = jj_consume_token(SUMA);
                  mostrarToken(t); {if (true) return "+";}
      break;
    case RESTA:
      t = jj_consume_token(RESTA);
                  mostrarToken(t); {if (true) return "-";}
      break;
    case MULT:
      t = jj_consume_token(MULT);
                  mostrarToken(t); {if (true) return "*";}
      break;
    case DIV:
      t = jj_consume_token(DIV);
                  mostrarToken(t); {if (true) return "/";}
      break;
    case MOD:
      t = jj_consume_token(MOD);
                  mostrarToken(t); {if (true) return "%";}
      break;
    default:
      jj_la1[25] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public Nodo valor() throws ParseException {
  Token t; Nodo n;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFICADOR:
      t = jj_consume_token(IDENTIFICADOR);
                          mostrarToken(t); n = new Nodo("valor", t.image); n.atributo("tipoValor", "identificador"); {if (true) return n;}
      break;
    case NUMERO:
      t = jj_consume_token(NUMERO);
                           mostrarToken(t); n = new Nodo("valor", t.image); n.atributo("tipoValor", "numero"); {if (true) return n;}
      break;
    case DECIMAL:
      t = jj_consume_token(DECIMAL);
                           mostrarToken(t); n = new Nodo("valor", t.image); n.atributo("tipoValor", "decimal"); {if (true) return n;}
      break;
    case CADENA:
      t = jj_consume_token(CADENA);
                           mostrarToken(t); n = new Nodo("valor", t.image); n.atributo("tipoValor", "cadena"); {if (true) return n;}
      break;
    case TRUE:
      t = jj_consume_token(TRUE);
                           mostrarToken(t); n = new Nodo("valor", t.image); n.atributo("tipoValor", "true"); {if (true) return n;}
      break;
    case FALSE:
      t = jj_consume_token(FALSE);
                           mostrarToken(t); n = new Nodo("valor", t.image); n.atributo("tipoValor", "false"); {if (true) return n;}
      break;
    case NULL:
      t = jj_consume_token(NULL);
                           mostrarToken(t); n = new Nodo("valor", t.image); n.atributo("tipoValor", "null"); {if (true) return n;}
      break;
    default:
      jj_la1[26] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  private boolean jj_2_7(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  private boolean jj_2_8(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  private boolean jj_2_9(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_9(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  private boolean jj_2_10(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_10(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  private boolean jj_2_11(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_11(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  private boolean jj_2_12(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_12(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(11, xla); }
  }

  private boolean jj_2_13(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_13(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(12, xla); }
  }

  private boolean jj_2_14(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_14(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(13, xla); }
  }

  private boolean jj_3_11() {
    if (jj_3R_20()) return true;
    return false;
  }

  private boolean jj_3_10() {
    if (jj_3R_19()) return true;
    return false;
  }

  private boolean jj_3R_38() {
    if (jj_3R_40()) return true;
    return false;
  }

  private boolean jj_3_9() {
    if (jj_3R_18()) return true;
    return false;
  }

  private boolean jj_3_8() {
    if (jj_3R_17()) return true;
    return false;
  }

  private boolean jj_3R_48() {
    if (jj_scan_token(PARENTESIS_IZQ)) return true;
    return false;
  }

  private boolean jj_3_7() {
    if (jj_3R_16()) return true;
    return false;
  }

  private boolean jj_3R_20() {
    if (jj_scan_token(BREAK)) return true;
    if (jj_scan_token(PUNTO_Y_COMA)) return true;
    return false;
  }

  private boolean jj_3_6() {
    if (jj_3R_15()) return true;
    return false;
  }

  private boolean jj_3_5() {
    if (jj_3R_14()) return true;
    return false;
  }

  private boolean jj_3R_23() {
    if (jj_scan_token(LLAVE_IZQ)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_38()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(LLAVE_DER)) return true;
    return false;
  }

  private boolean jj_3R_47() {
    if (jj_3R_49()) return true;
    return false;
  }

  private boolean jj_3R_46() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_47()) {
    jj_scanpos = xsp;
    if (jj_3R_48()) return true;
    }
    return false;
  }

  private boolean jj_3_4() {
    if (jj_3R_13()) return true;
    return false;
  }

  private boolean jj_3_3() {
    if (jj_3R_12()) return true;
    return false;
  }

  private boolean jj_3_2() {
    if (jj_3R_11()) return true;
    return false;
  }

  private boolean jj_3_1() {
    if (jj_3R_10()) return true;
    return false;
  }

  private boolean jj_3R_36() {
    if (jj_scan_token(PRINTLN)) return true;
    return false;
  }

  private boolean jj_3R_45() {
    if (jj_3R_46()) return true;
    return false;
  }

  private boolean jj_3R_35() {
    if (jj_scan_token(PRINT)) return true;
    return false;
  }

  private boolean jj_3R_40() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_1()) {
    jj_scanpos = xsp;
    if (jj_3_2()) {
    jj_scanpos = xsp;
    if (jj_3_3()) {
    jj_scanpos = xsp;
    if (jj_3_4()) {
    jj_scanpos = xsp;
    if (jj_3_5()) {
    jj_scanpos = xsp;
    if (jj_3_6()) {
    jj_scanpos = xsp;
    if (jj_3_7()) {
    jj_scanpos = xsp;
    if (jj_3_8()) {
    jj_scanpos = xsp;
    if (jj_3_9()) {
    jj_scanpos = xsp;
    if (jj_3_10()) {
    jj_scanpos = xsp;
    if (jj_3_11()) {
    jj_scanpos = xsp;
    if (jj_3_12()) {
    jj_scanpos = xsp;
    if (jj_3_13()) {
    jj_scanpos = xsp;
    if (jj_3_14()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_13() {
    if (jj_scan_token(IF)) return true;
    if (jj_scan_token(PARENTESIS_IZQ)) return true;
    return false;
  }

  private boolean jj_3R_19() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_35()) {
    jj_scanpos = xsp;
    if (jj_3R_36()) return true;
    }
    if (jj_scan_token(PARENTESIS_IZQ)) return true;
    return false;
  }

  private boolean jj_3R_44() {
    if (jj_scan_token(RESTA)) return true;
    return false;
  }

  private boolean jj_3R_43() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_44()) {
    jj_scanpos = xsp;
    if (jj_3R_45()) return true;
    }
    return false;
  }

  private boolean jj_3R_34() {
    if (jj_scan_token(DECREMENTO)) return true;
    return false;
  }

  private boolean jj_3R_33() {
    if (jj_scan_token(INCREMENTO)) return true;
    return false;
  }

  private boolean jj_3R_18() {
    if (jj_scan_token(SWITCH)) return true;
    if (jj_scan_token(PARENTESIS_IZQ)) return true;
    return false;
  }

  private boolean jj_3R_12() {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_33()) {
    jj_scanpos = xsp;
    if (jj_3R_34()) return true;
    }
    return false;
  }

  private boolean jj_3R_42() {
    if (jj_3R_43()) return true;
    return false;
  }

  private boolean jj_3R_56() {
    if (jj_scan_token(NULL)) return true;
    return false;
  }

  private boolean jj_3R_55() {
    if (jj_scan_token(FALSE)) return true;
    return false;
  }

  private boolean jj_3R_54() {
    if (jj_scan_token(TRUE)) return true;
    return false;
  }

  private boolean jj_3R_53() {
    if (jj_scan_token(CADENA)) return true;
    return false;
  }

  private boolean jj_3R_52() {
    if (jj_scan_token(DECIMAL)) return true;
    return false;
  }

  private boolean jj_3R_51() {
    if (jj_scan_token(NUMERO)) return true;
    return false;
  }

  private boolean jj_3R_50() {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    return false;
  }

  private boolean jj_3R_49() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_50()) {
    jj_scanpos = xsp;
    if (jj_3R_51()) {
    jj_scanpos = xsp;
    if (jj_3R_52()) {
    jj_scanpos = xsp;
    if (jj_3R_53()) {
    jj_scanpos = xsp;
    if (jj_3R_54()) {
    jj_scanpos = xsp;
    if (jj_3R_55()) {
    jj_scanpos = xsp;
    if (jj_3R_56()) return true;
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_11() {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    if (jj_scan_token(ASIGNACION)) return true;
    return false;
  }

  private boolean jj_3R_17() {
    if (jj_scan_token(FOREACH)) return true;
    if (jj_scan_token(PARENTESIS_IZQ)) return true;
    return false;
  }

  private boolean jj_3R_41() {
    if (jj_3R_42()) return true;
    return false;
  }

  private boolean jj_3R_32() {
    if (jj_scan_token(BYTE)) return true;
    return false;
  }

  private boolean jj_3R_15() {
    if (jj_scan_token(FOR)) return true;
    if (jj_scan_token(PARENTESIS_IZQ)) return true;
    return false;
  }

  private boolean jj_3R_39() {
    if (jj_3R_41()) return true;
    return false;
  }

  private boolean jj_3R_31() {
    if (jj_scan_token(SHORT)) return true;
    return false;
  }

  private boolean jj_3R_30() {
    if (jj_scan_token(LONG)) return true;
    return false;
  }

  private boolean jj_3R_29() {
    if (jj_scan_token(FLOAT)) return true;
    return false;
  }

  private boolean jj_3R_28() {
    if (jj_scan_token(DOUBLE)) return true;
    return false;
  }

  private boolean jj_3R_27() {
    if (jj_scan_token(CHAR)) return true;
    return false;
  }

  private boolean jj_3R_26() {
    if (jj_scan_token(STRING)) return true;
    return false;
  }

  private boolean jj_3R_25() {
    if (jj_scan_token(BOOLEAN)) return true;
    return false;
  }

  private boolean jj_3R_37() {
    if (jj_3R_39()) return true;
    return false;
  }

  private boolean jj_3R_24() {
    if (jj_scan_token(INT)) return true;
    return false;
  }

  private boolean jj_3R_16() {
    if (jj_scan_token(DO)) return true;
    if (jj_3R_23()) return true;
    return false;
  }

  private boolean jj_3R_22() {
    if (jj_scan_token(RETURN)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_37()) jj_scanpos = xsp;
    if (jj_scan_token(PUNTO_Y_COMA)) return true;
    return false;
  }

  private boolean jj_3R_10() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_24()) {
    jj_scanpos = xsp;
    if (jj_3R_25()) {
    jj_scanpos = xsp;
    if (jj_3R_26()) {
    jj_scanpos = xsp;
    if (jj_3R_27()) {
    jj_scanpos = xsp;
    if (jj_3R_28()) {
    jj_scanpos = xsp;
    if (jj_3R_29()) {
    jj_scanpos = xsp;
    if (jj_3R_30()) {
    jj_scanpos = xsp;
    if (jj_3R_31()) {
    jj_scanpos = xsp;
    if (jj_3R_32()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    if (jj_scan_token(IDENTIFICADOR)) return true;
    return false;
  }

  private boolean jj_3R_21() {
    if (jj_scan_token(CONTINUE)) return true;
    if (jj_scan_token(PUNTO_Y_COMA)) return true;
    return false;
  }

  private boolean jj_3_14() {
    if (jj_3R_23()) return true;
    return false;
  }

  private boolean jj_3_13() {
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3R_14() {
    if (jj_scan_token(WHILE)) return true;
    if (jj_scan_token(PARENTESIS_IZQ)) return true;
    return false;
  }

  private boolean jj_3_12() {
    if (jj_3R_21()) return true;
    return false;
  }

  /** Generated Token Manager. */
  public TraductorTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  /** Whether we are looking ahead. */
  private boolean jj_lookingAhead = false;
  private boolean jj_semLA;
  private int jj_gen;
  final private int[] jj_la1 = new int[27];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0xffb83fa0,0xff800000,0x0,0x0,0x40,0x3800000,0x4000,0x8000,0xffb83fa0,0xffb83fa0,0x70000,0x0,0x180000,0xffb83fa0,0x0,0x0,0x70000,0x0,0x0,0x0,0x0,0x70000,0x70000,0x0,0x0,0x0,0x70000,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x40080000,0x0,0x800,0x3000,0x0,0x0,0x0,0x0,0x40080000,0x40080000,0x78020080,0x3800,0x0,0x40080000,0x8000,0x4000,0x78030080,0x3f,0x3f,0xc0,0x700,0x78020080,0x78020000,0xc0,0x700,0x7c0,0x78000000,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[14];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public Traductor(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Traductor(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new TraductorTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 27; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 27; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public Traductor(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new TraductorTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 27; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 27; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public Traductor(TraductorTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 27; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(TraductorTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 27; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = jj_lookingAhead ? jj_scanpos : token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List jj_expentries = new java.util.ArrayList();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      boolean exists = false;
      for (java.util.Iterator it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          exists = true;
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              exists = false;
              break;
            }
          }
          if (exists) break;
        }
      }
      if (!exists) jj_expentries.add(jj_expentry);
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[63];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 27; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 63; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 14; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
            case 7: jj_3_8(); break;
            case 8: jj_3_9(); break;
            case 9: jj_3_10(); break;
            case 10: jj_3_11(); break;
            case 11: jj_3_12(); break;
            case 12: jj_3_13(); break;
            case 13: jj_3_14(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
